// <auto-generated />
using AFisherWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AFisherWebApp.Migrations
{
    [DbContext(typeof(FisherAndrewDBContext))]
    [Migration("20240229155534_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("AFisherWebApp.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Rank = 1,
                            Title = "A Head Full of Dreams"
                        });
                });

            modelBuilder.Entity("AFisherWebApp.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("AFisherWebApp.Models.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntityId = 7,
                            Text = "\"It was just time for us to make an album about hope and love and togetherness\"-Chris Martin. A Head Full of Dreams is my favorite Coldplay Album, and its central theme is the graduation and application of the hopeful yearning found in past albums. A Head Full of Dreams stand in contrast as the day to the night that was Ghost Stories. Ghost Stories was raw and depressing and overwhelmingly dark, AHFOD enlightens us once again to the joy found in everyday life. The album cover alone, with its rainbow circle of life, bursting with color is directly contrasted to the darkness that was Ghost Stories. \"A Head Full of Dreams,\" \"Birds\" and \"Fun\" are upbeat and hopeful alternative hits that draw us into the irrepressible happiness of the album. At the same time, songs like \"Hymn for the Weekend\" and \"Adventure a Lifetime\" fuse conventional alternative with bright and colorful pop-rock. Musically, \"Birds\" and \"Up&Up\" draw you in with their driven beats and uplifting chords, while \"Amazing Day\" surrounds you with feelings of peaceful love."
                        });
                });

            modelBuilder.Entity("AFisherWebApp.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alt = "Album Cover, A Head Full of Dreams - Coldplay",
                            EntityId = 7,
                            Src = "/music/coldplay-albums/a-head-full-of-dreams.jpg"
                        });
                });

            modelBuilder.Entity("AFisherWebApp.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppleURI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpotifyURI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppleURI = "a-head-full-of-dreams/1053933969",
                            EntityId = 7,
                            SpotifyURI = "3cfAM8b8KqJRoIzt3zLKqw"
                        });
                });

            modelBuilder.Entity("AFisherWebApp.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Coloratura, Let Somebody Know",
                            EntityId = 7,
                            Title = "Favorite Tracks:"
                        });
                });

            modelBuilder.Entity("AFisherWebApp.Models.Content", b =>
                {
                    b.HasOne("AFisherWebApp.Models.Album", null)
                        .WithMany("Contents")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AFisherWebApp.Models.Artist", null)
                        .WithMany("Contents")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AFisherWebApp.Models.Image", b =>
                {
                    b.HasOne("AFisherWebApp.Models.Album", null)
                        .WithOne("Image")
                        .HasForeignKey("AFisherWebApp.Models.Image", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AFisherWebApp.Models.Artist", null)
                        .WithOne("Image")
                        .HasForeignKey("AFisherWebApp.Models.Image", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AFisherWebApp.Models.Link", b =>
                {
                    b.HasOne("AFisherWebApp.Models.Album", null)
                        .WithOne("Links")
                        .HasForeignKey("AFisherWebApp.Models.Link", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AFisherWebApp.Models.Artist", null)
                        .WithOne("Links")
                        .HasForeignKey("AFisherWebApp.Models.Link", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AFisherWebApp.Models.Tag", b =>
                {
                    b.HasOne("AFisherWebApp.Models.Album", null)
                        .WithMany("Tags")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AFisherWebApp.Models.Artist", null)
                        .WithMany("Tags")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AFisherWebApp.Models.Album", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Links")
                        .IsRequired();

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("AFisherWebApp.Models.Artist", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Links")
                        .IsRequired();

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
